# Path to metadata and sequences previously extracted in DMS repo
metadata: "my_profiles/LASV_Josiah_GP_DMS/non-pipeline_analyses/LASV_phylogeny_analysis/Results/LASV_S_segment_metadata.tsv"
GPC_codon_sequences: "my_profiles/LASV_Josiah_GP_DMS/non-pipeline_analyses/LASV_phylogeny_analysis/Results/LASV_GPC_codon.fasta"

# DMSA phenotype prediction
# dictionary of phenotype collections
# each collection has a name and a set of parameters
# For a number of individual experiemnts.
dmsa_phenotype_collections:
  all-sera:
    # directory containing escape csv's
    mut_effects_dir: "my_profiles/LASV_Josiah_GP_DMS/results/filtered_antibody_escape_CSVs"
    # name of the column containing the effect score
    mut_effect_col: "escape_median_floor_zero"
    # name of the column containing the mutation
    mutation_col: "mutation"
